Repository mcanouil/awesome-quarto, pull requests merged in 2023-03, with the labels that each got.

#285 added four extensions
  README.md
Labels: suggestion

#288 fiw: rm website not existing anymore
  README.md
Labels: bug

#286 Add quarto-brief
  README.md
Labels: suggestion

#287 Add bookup custom HTML format
  README.md
Labels: suggestion

#289 fix: compact-pdf Quarto Format
  README.md
Labels: suggestion

#291 feat: set featured
  README.md
Labels: release
